### ISSUE TITLE
Drag and drop doesn't work to customise a filter set.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/SpekCheck#78] opened 2018-06-07 15:34 UTC
Drag and drop filter functionality doesn't work on Chrome on a mac

**Comment by iandobbie** [comment] 2018-06-07 15:35
Or Safari.

**Comment by carandraug** [comment] 2018-06-09 22:03
Fixed with f08aabe

This was a weird bug because it works on chrome if running locally from `file://`, it can only be reproduced with a web server.

On dragstart, we set the datastore with the filter name. During dragover, we were checking the contents on datastore for a valid filter name (in case one day we have more drag and drop elements), and the fnew filter is added ondrop.  However, Chrome does not allow inspection of the datastore during dragover.  The reason seems to be security, to prevent iframes from accessing the datastore if a user drags something over them by accident.

Anyway, fixed now.

**Closed by carandraug** 2018-06-09 22:03 UTC
